<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Field {name} is Created' => 'Поле {name} Создано',
    'Add New' => 'Добавить Новый',
    'Add New Setting' => 'Добавить Новую Настройку',
    'Build {modelClass}: ' => 'Конструктор {modelClass}:',
    'Build' => 'Конструктор',
    'Cancel' => 'Отмена',
    'Type' => 'Тип',
    'Choose Type' => 'Выберите Тип',
    'Delete this Menu item?' => 'Удалить Этот Пункт Меню?',
    'Choose Icon Class:' => 'Выбрать Класс Иконки:',
    'How To Use:' => 'Как использовать:',
    'Icon Name' => 'Название значка',
    'Menu Item Name' => 'Название Пункта Меню',
    'Menu Item Url' => 'Урл Пункта Меню ',
    'Moved {name} order down' => 'Перемещен {name} уровень вниз',
    'Moved {name} order up' => 'Перемещен {name} уровень вверх',
    'New Menu' => 'Новое Меню',
    'New Menu Item' => 'Пункт Нового Меню',
    'Open In' => 'Открыть в',
    'Save Sattings' => 'Сохранить Настройки',
    'Setting key:' => 'Ключ настройки:',
    'Setting name:' => 'Имя Настройки:',
    'Success' => 'Успешно',
    'Browse' => 'Выбрать',
    'Current window' => 'Текушее окно',
    'New window' => 'Новое окно',
    'Create a New Menu Item' => 'Создание Нового Пункта Меню',
    'Success fully updated menu order.' => 'Успешно полностью обновленный порядок меню',
    'This is already at the bottom of the list' => 'Это уже в нижней части списка',
    'This is already at the top of the list' => 'Это уже в верхней части списка',
    'This item not find!' => 'Этот пункт не найти!',
    'This name is exist' => 'Это имя существует',
    'You can get the value of each setting anywhere on your site by calling' => 'Вы можете получить значение каждой настройки в любом месте вашего сайта, вызвав',
    'You can output this menu anywhere on your site by calling ' => 'Вы можете выводить это меню в любом месте вашего сайта, вызывая',
    'Application Name' => '@@Имя Приложения@@',
    'Date format' => 'Формат Даты',
    'E-mail Adress' => 'E-mail Адресс',
    'General Settings' => 'Общие Настройки',
    'Maximum number of posts per page' => 'Максимальное количество сообщений на странице',
    'Page' => 'Страница',
    'Save' => 'Сохранить',
    'Short description' => 'Краткое Описание',
    'Timezone' => 'Часовой пояс',
    'User' => 'Пользователь',
    'All User' => 'Все Пользователи',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Assignments' => 'Назначения',
    'Open' => 'Открыть',
    'Available?' => 'Доступный',
    'Create' => 'Создать',
    'Create Page' => 'Новая Страница',
    'Dashboard' => 'Панель Управления',
    'Delete' => 'Удалить',
    'File Manager' => 'Файловый менеджер',
    'Files' => 'Файлы',
    'Menu' => 'Меню',
    'Pages' => 'Страницы',
    'Permission' => 'Разрешение',
    'Reset' => 'Сброс',
    'Reset Grid' => 'Сбросить Сетку',
    'Role' => 'Роль',
    'Route' => 'Роут',
    'Rules' => 'Правила',
    'SECTION 1: Identification Information' => 'РАЗДЕЛ 1: Идентификационная Информация',
    'SECTION 2: Content Information' => 'РАЗДЕЛ 2: Информация о Контенте',
    'Search' => 'Поиск',
    'Settings' => 'Настройки',
    'Update' => 'Обновить',
    'Update: ' => 'Обновить: ',
    'User Manager' => 'Менеджер Пользователей',
];
